name: GitHub Actions Demo
run-name: ${{ github.actor }} testing the project
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          make build
